language: perl
perl:
  - 5.18
  - 5.16
  - 5.14
install:
  - cpanm -nq --installdeps .
  - cpanm -nq Devel::Cover::Report::Coveralls
script:
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine dzil test
  - cover
after_success:
  - cover -report coveralls
