language: perl
perl:
  - 5.18
  - 5.16
  - 5.14
install:
  - cpanm -nq Devel::Cover::Report::Coveralls
  - cpanm Dist::Zilla
  - dzil authordeps --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
  - dzil listdeps --author --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
script:
  - HARNESS_PERL_SWITCHES=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine,-db,$TRAVIS_BUILD_DIR/cover_db dzil test --author --release
  - cover
after_success:
  - cover -report coveralls
